/*
 Ras Web Viewer - ver. 2.2.2 - 03.11.2022.
 Copyright Ras Timetable Software. All Rights Reserved.
 http://time-table.net
*/
var U;
(function(a){function d(a){a=b(a);return[parseInt(a.substring(0,2),16),parseInt(a.substring(2,4),16),parseInt(a.substring(4,6),16)]}function b(a){"#"==a.charAt(0)&&(a=a.substring(1,7));6!=a.length&&(a=a.charAt(0)+a.charAt(0)+a.charAt(1)+a.charAt(1)+a.charAt(2)+a.charAt(2));return a}function c(a){return(a=_DB.general.loc[a])?a:""}function g(a){return!isNaN(parseFloat(a))&&isFinite(a)}a.isLtIE9=function(){return document.addEventListener?!1:!0};a.getBrightness=function(a){a=d(a);return(299*a[0]+587*
a[1]+114*a[2])/1E3};a.getRGB=d;a.cutHex=b;a.getPageSize=function(){var a,b;window.innerHeight&&window.scrollMaxY?(a=window.innerWidth+window.scrollMaxX,b=window.innerHeight+window.scrollMaxY):document.body.scrollHeight>document.body.offsetHeight?(a=document.body.scrollWidth,b=document.body.scrollHeight):(a=document.body.offsetWidth,b=document.body.offsetHeight);var c,d;self.innerHeight?(c=document.documentElement.clientWidth?document.documentElement.clientWidth:self.innerWidth,d=self.innerHeight):
document.documentElement&&document.documentElement.clientHeight?(c=document.documentElement.clientWidth,d=document.documentElement.clientHeight):document.body&&(c=document.body.clientWidth,d=document.body.clientHeight);return[a<c?a:c,b<d?d:b,c,d]};a.getLoc=c;a.getDayName=function(a){return c("day"+(a+1))};a.getRealDuration=function(a,b){var c=a+b-_opt.brCas;0<c&&(b-=c);return b};a.getUrlParam=function(a){a=(new RegExp("[?&]"+a+"=([^&#]*)")).exec(window.location.href);return null==a?"":a[1]||""};a.isNumeric=
g;var f="I II III IV V VI VII VIII IX X XI XII".split(" "),e="\u2160\u2161\u2162\u2163\u2164\u2165\u2166\u2167\u2168\u2169\u216a\u216b".split("");a.romanKeyToRomanStr=function(a){var b=a.toUpperCase(),b=f.indexOf(b);return 0<=b?e[b]:a};a.toRomanNum=function(a){var b=parseInt(a,10);if(!g(b)||1>b||12<b)return a;b--;return e[b]}})(U||(U={}));var _DB,_opt,g_blok,g_fontSize,g_$td=null,g_view,g_hasKabi=!1;function getRes(a){return _DB[{n:"teachers",o:"classes",k:"rooms"}[a]]}
$(document).ready(function(){if(_DB)if(_DB.err)$("body").append('<div class="error">'+_DB.err+"</div>");else{var a=_DB.general;_opt={brDan:a.day_count,brCas:a.per_count,rbr:a.rbr.split(","),shift:a.shift,bells:a.bells,clRoman:void 0===a.clRoman?!1:a.clRoman,clIndex:void 0===a.clIndex?!0:a.clIndex};0<_DB.rooms.length&&_DB.rooms[0][3]&&(g_hasKabi=!0);var d=U.getLoc("rascas");document.title=d.charAt(0).toLocaleUpperCase()+d.slice(1).toLocaleLowerCase();d=$("#title-left");d.append('<span id="school-name">'+
a.school+"</span><br/>");d.append(U.getLoc("skgod")+" "+a.year+"<br/>");d.append(a.shift);$("#title-center").append("<h1>"+U.getLoc("rascas")+"</h1 >"+U.getLoc("vazi")+" "+a.date);$("label[for=r1]").append(U.getLoc("nast"));$("label[for=r2]").append(U.getLoc("odel"));g_hasKabi&&$("#radios").append("<br/><input type='radio' id='r3' name='izbor' value='k' /><label for='r3' class='tb-item'>"+U.getLoc("kabis")+"</label>");$("input:radio[name='izbor']").change(function(a){a=$(this).val();changeView(a,
"radio")});$("#printer").click(function(){printRas();return!1});a='<select id="select" class="tb-item"><option value="n">'+U.getLoc("nast")+'</option><option value= "o">'+U.getLoc("odel")+"</option>";g_hasKabi&&(a+='<option value="k">'+U.getLoc("kabis")+"</option>",a+="</select>");$("#combo").html(a);$("#select").change(function(){var a=$(this).val();changeView(a,"combo")});setMainTable("n","#raspored_nast");setMainTable("o","#raspored_odel");g_hasKabi&&setMainTable("k","#raspored_kabi");g_blok=_opt.brCas;
g_fontSize=90;setFontSize();$(".mainTable th.headCelPer").css("font-size",g_fontSize+"%");$(".mainTable th.headCelPerEven").css("font-size",g_fontSize+"%");$(".mainTable td").not(".rasCelOdel,.rasCelNast,.rbr").css("font-size",g_fontSize+"%");$(window).resize(function(){waitForFinalEvent(function(){doResize()},500,"some unique string")});$(".mainTable td.rasCelNast, .mainTable td.rasCelOdel").click(function(){loadPopup($(this))});$("div.close").click(function(){disablePopup()});$(this).keyup(function(a){27==
a.which&&disablePopup()});$("div#backgroundPopup").click(function(){disablePopup()});$("#screen-container").removeClass("hidden");changeView(U.getUrlParam("v"),"fromUrl")}else $("body").append('<div class="error">Ovaj raspored nije objavljen!</div>')});function changeUrl(a){if("undefined"!==typeof history.replaceState){var d="?pid="+U.getUrlParam("pid")+"&v="+g_view;a&&(d+="&i="+a);a={Page:$(document).attr("title"),Url:d};history.replaceState(a,a.Page,a.Url)}}
function doResize(){setFontSize();$(".headCelPer").css("font-size",g_fontSize+"%");$(".headCelPerEven").css("font-size",g_fontSize+"%");$(".mainTable td").not(".rasCelOdel,.rasCelNast,.rbr").css("font-size",g_fontSize+"%");setPopupPos()}
function setFontSize(){var a=[70,100];U.isLtIE9()&&(a=[50,80]);var d=(U.getPageSize()[0]-200)/(_opt.brDan*_opt.brCas),b=g_fontSize;g_fontSize=Math.round(100*d/24*10)/10;g_fontSize>a[1]&&(g_fontSize=a[1]);g_fontSize<a[0]&&(g_fontSize=a[0]);return b!==g_fontSize?!0:!1}var waitForFinalEvent=function(){var a={};return function(d,b,c){c||(c="Don't call this twice without a uniqueId");a[c]&&clearTimeout(a[c]);a[c]=setTimeout(d,b)}}();
function changeView(a,d){a||(a="n");g_hasKabi||"k"!==a||(a="n");g_view=a;var b;"n"===g_view?($("#raspored_nast").fadeIn(),$("#raspored_odel").hide(),$("#raspored_kabi").hide(),g_view="n",b=$("#nast-name")):"o"===g_view?($("#raspored_nast").hide(),$("#raspored_odel").fadeIn(),$("#raspored_kabi").hide(),g_view="o",b=$("#odel-name")):($("#raspored_nast").hide(),$("#raspored_odel").hide(),$("#raspored_kabi").fadeIn(),g_view="k",b=$("#kabi-name"));$("input:radio[name=izbor]").filter('[value="'+g_view+
'"]').prop("checked",!0);$("#combo").css({top:b.offset().top+2,left:b.offset().left+2});var c=$("#select");c.css({width:b.width()-3,height:b.height()-3});c.val()!==g_view&&c.val(g_view);"fromUrl"===d?(b=U.getUrlParam("i"))&&loadPopup(getTD(b),!0):changeUrl()}
function loadPopup(a,d){if(0!==a.length&&!g_$td){g_$td=a;$("#loadme").html(getTooltip());if(d){var b=$("#"+(g_view+"_0")+" td:nth-child(2)");setPopupPos(b.offset().top+b.height()-5)}else setPopupPos(),changeUrl(getEntyID(getInd()));$("#toPopup").fadeIn(200);$("#backgroundPopup").css("opacity","0.15");$("#backgroundPopup").fadeIn(200)}}
function setPopupPos(a){if(g_$td){var d=$("#toPopup"),b=70;"n"!==g_view&&(b=100);b*=_opt.brCas+1;800<b&&(b=800);d.css("width",b);a=void 0!==a?a:g_$td.offset().top+g_$td.height()-5;var c=d.outerHeight(),b=$(document).scrollTop(),c=b+$(window).height()-(a+c);0>c&&(a+=c-5);a<b&&(a=b);var b=g_$td.offset().left+g_$td.width(),g=d.outerWidth(),c=$(document).scrollLeft(),g=c+$(window).width()-(b+g);0>g&&(b+=g-5);b<c&&(b=c);d.css({top:a,left:b})}}
function disablePopup(){g_$td&&($("#toPopup").fadeOut(200),$("#backgroundPopup").fadeOut(200),g_$td=null,changeUrl())}function getEntyID(a){return"i"+a}function getTD(a){a=a.substring(1);return $("#"+(g_view+"_"+a)+" td:nth-child(2)")}function getInd(){var a=g_$td.parent().attr("id");return parseInt(a.substring(2))}function setMainTable(a,d){var b="<table class='mainTable'>"+GetTTHeader(a),b=b+GetTTBody(a),b=b+"</table>";$(d).append(b)}
function GetTTHeader(a){var d;d="<thead><tr>"+("<th class='headCelDay' style='width:20px' rowspan='2'>"+U.getLoc("rbr")+"</th>");var b="razmak";"n"===a?d+="<th id='nast-name' class='headCelDay' style='width:10em' rowspan='2'>"+U.getLoc("prez_ime")+"</th>":"o"===a?(d+="<th  id='odel-name' class='headCelDay combo' style='width:5em' rowspan='2'>"+U.getLoc("odel")+"</th>",b="razmakOdel"):d+="<th id='kabi-name' class='headCelDay' style='width:10em' rowspan='2'>"+U.getLoc("kabi")+"</th>";a="<th class='"+
b+"'></th>";for(b=0;b<_opt.brDan;b++){d+=a;d+="<th";var c=0===b%2?"headCelDayEven":"headCelDay";d+=" class='"+c+"'";d+=" colspan='"+_opt.brCas+"'>";d+=U.getDayName(b);d+="</th>"}d+="</tr><tr>";for(b=0;b<_opt.brDan;b++){d+=a;for(var g=0;g<_opt.brCas;g++)c=0===b%2?"headCelPerEven":"headCelPer",d+="<th class='"+c+"'>",d+=_opt.rbr[g],d+="</th>"}return d+"</tr></thead>"}function GetTTBody(a){for(var d=getRes(a),b="<tbody>",c=0,g=d.length;c<g;c++)b+=GetTTRow(a,c,d[c]);return b+"</tbody>"}
function GetTTRow(a,d,b){var c="o"===a,g="rasCelNast",f="razmak";"n"===a?a="n_"+d:"o"===a?(a="o_"+d,g="rasCelOdel",f="razmakOdel"):a="k_"+d;f="<th class='"+f+"'></th>";d=""+("<tr class='dataRow' id='"+a+"'>")+("<td class='rbr'>"+(d+1)+".</td>")+("<td class='"+g+"' rel='#loadme'>");d+=c?formatClassName(b[0],1):b[0];d+="</td>";a=g=0;b=b[3];for(var e=0,h=b.length;e<h;e++){var k=b[e],l=k[0],m=k[1],n=k[2];d+=fillEmpty(g,a,l,m,f);0===m&&(d+=f);d+=getCardHtml(c,k);g=l;a=m;a+=U.getRealDuration(m,n)}d+=fillEmpty(g,
a,_opt.brDan-1,_opt.brCas,f);return d+="</tr>"}function fillEmpty(a,d,b,c,g){var f=_opt.brCas,e="";b=b*f+c;for(a=a*f+d;a<b;a++){d=Math.floor(a/f);c=a%f;0===c&&(e+=g);var h=" class='od'";f>=f?0==d%2&&(h=" class='ev'"):0>=f?0==c%2&&(h=" class='ev'"):0==c/f%2&&(h=" class='ev'");e+="<td"+h+"></td>"}return e}
function getCardHtml(a,d){var b=U.getRealDuration(d[1],d[2]),c="<td";1<b&&(c+=" colspan='"+b+"'");c+="><div class='crd'>";b=d[3];if($.isArray(b))for(var g=b.length,f=3/g,e=0;e<g;e++){c+="<div style='";3<g&&(f=100-6*g,c+="font-size:"+f+"%;",f/=80);var c=c+("line-height:"+f+"em;"),c=c+("height:"+f+"em;"),c=c+"' class='slozena'",c=c+">",h=b[e][0],c=c+(a?_DB.subjects[h][1]:formatClassName(_DB.classes[h][0],g)),c=c+"</div>"}else c=c+"<div class='obicna'>"+(a?_DB.subjects[b][1]:formatClassName(_DB.classes[b][0],
1)),c+="</div>";return c+"</div></td>"}function formatClassName(a,d){if(!_opt.clRoman&&!_opt.clIndex)return a;var b=a.indexOf("/"),c=a.indexOf("-");0<c&&(0>b||b>c)&&(b=c);if(0<=b)if(c=U.romanKeyToRomanStr(a.substring(0,b)),_opt.clRoman&&(c=U.toRomanNum(c)),_opt.clIndex){var g=2<d?"</small>":"</sub>";a=c+(2<d?"<small>":"<sub>")+a.substring(b+1)+g}else a=c+a.substring(b);return a}
function getTooltip(){var a=g_view,d=80,b,c;b=getRes(a);var g=getInd(),f=b[g];"o"!==a?(12<_opt.brCas&&(d=70),b="<h2>"+f[0]+"</h2>",c="n"===a?f[1]:f[2],"n"===a?(0<=c&&(b+='<div id="toolLeft">'+_DB.subjects[c][0]+"</div>"),a=getNastToolCardHTML,c=f[2],0<=c&&(b+='<div id="toolRight">'+_DB.general.loc.kabi+": "+_DB.rooms[c][0]+"</div>")):(0<=c&&(b+='<div id="toolCenter">'+_DB.subjects[c][0]+"</div>"),a=getKabiToolCardHTML),c="toolTable"):(a=getOdelToolCardHTML,b="<h2>"+formatClassName(f[0],1)+"</h2>",
c=f[2],b+='<div id="toolCenter">'+(0<=c?_DB.general.loc.razr+": "+_DB.teachers[c][0]:"&nbsp")+"</div>",c="toolTable-o");b=b+('<div id="print-tool"><a href="javascript:void(0);" onclick="printRas();">Print</a></div>'+('<table class="'+c+'">'))+"<thead><tr>";b+="<th></th>";for(c=0;c<_opt.brCas;c++){b+="<th>"+_opt.rbr[c];var e=_opt.bells;e&&(b+='<br/><span style="font-size:'+d+'%">',""!==e[c][0].trim()&&(b+=e[c][0]+"-"+e[c][1]),""!==e[c][2].trim()&&(b+="<br/>"+e[c][2]+"-"+e[c][3]),b+="</span>");b+="</th>"}b+=
"</tr>";b+="</thead>";b+="<tbody>";for(var d=f[3],e=0,f=0<d.length?d[0]:null,h=0;h<_opt.brDan;h++){b+="<tr>";b+="<th>"+_DB.general.loc["day"+(h+1)].substring(0,3)+"</th>";for(c=0;c<_opt.brCas;c++)null!==f&&f[0]===h&&f[1]===c?(b+=a(f,g),1<f[2]&&(c+=f[2]-1),e++,f=d.length>e?d[e]:null):(b+="<td",g_blok<_opt.brCas&&0<g_blok&&0!==Math.floor(c/g_blok)%2&&(b+=' class="od"'),b+="></td>");b+="</tr>"}b+="</tbody>";return b+"</table>"}
function getNastToolCardHTML(a,d){var b="<td";1<a[2]&&(b+=' colspan="'+a[2]+'"');var b=b+">",c=$.isArray(a[3])?a[3]:[[a[3],-1]],g=36/c.length,f=c[0][0],e=a[4],h=_DB.classes[f][1],f="";e!==_DB.teachers[d][1]&&(f='<span class="pki">'+_DB.subjects[e][1]+"</span>");e='<div class="toolCard" style="background-color:'+h+';"><div class="pk"';128>=U.getBrightness(h)&&(e+=' style="color:white;"');for(var e=e+">"+f+"</div>",k=c.length,l=0;l<k;l++)f=c[l][0],e+='<div class="toolCard_block" style="',e+="background-color:"+
_DB.classes[f][1]+";",e+="line-height:"+g+"px;",e+="height:"+g+"px;",1<k&&(e+="margin:0 1px;",3<k&&(e+="font-size:"+(100-6*k)+"%;")),128>=U.getBrightness(_DB.classes[f][1])&&(e+="color:white;"),e+='">',e+=formatClassName(_DB.classes[f][0],k),0<=c[l][1]&&(e+='<span class="pk">-'+_DB.classes[f][4][c[l][1]]+"</span>"),e+="</div>";c=a[5];g="";0<=c&&c!==_DB.teachers[d][2]&&(g='<span class="pki">'+_DB.rooms[c][1]+"</span>");e+='<div class="pk"';128>=U.getBrightness(h)&&(e+=' style="color:white;"');e+=">";
e+=g;e+="</div>";e+="</div>";b+=e;return b+"</td>"}
function getOdelToolCardHTML(a,d){var b="<td";1<a[2]&&(b+=' colspan="'+a[2]+'"');for(var b=b+'><div class="toolCellOdel">',c=$.isArray(a[3])?a[3]:[[a[3],a[4],-1]],g=6/c.length,f=0;f<c.length;f++){var e=c[f][0],b=b+('<div style="overflow:hidden;height:'+g+"em;background-color:"+_DB.subjects[e][2]+";");128>=U.getBrightness(_DB.subjects[e][2])&&(b+="color:white;");var b=b+'">',h=c[f][1];0<=h&&(b+='<div class="kab"><span class="kab">'+_DB.rooms[h][1]+"</span></div>");b+='<table class="cellTable">';b+=
'<tr><td style="height:'+(g-(0<=h?1:0)).toString()+'em;">';0<=c[f][2]&&(b+='<span class="pk">'+_DB.classes[d][4][c[f][2]]+":");b+=_DB.subjects[e][0]+"</span>";b+="</td></tr></table></div>"}return b+"</div></td>"}
function getKabiToolCardHTML(a,d){var b="<td";1<a[2]&&(b+=' colspan="'+a[2]+'"');var b=b+">",c=$.isArray(a[3])?a[3]:[[a[3],-1]],g=36/c.length,f=c[0][0],e=a[4],h=_DB.classes[f][1],f="";e!==_DB.rooms[d][2]&&(f='<span class="pki">'+_DB.subjects[e][1]+"</span>");e='<div class="toolCard" style="background-color:'+h+';"><div class="pk"';128>=U.getBrightness(h)&&(e+=' style="color:white;"');for(var e=e+">"+f+"</div>",k=c.length,l=0;l<k;l++)f=c[l][0],e+='<div class="toolCard_block" style="',e+="background-color:"+
_DB.classes[f][1]+";",e+="line-height:"+g+"px;",e+="height:"+g+"px;",1<k&&(e+="margin:0 1px;"),128>=U.getBrightness(_DB.classes[f][1])&&(e+="color:white;"),e+='">',e+=formatClassName(_DB.classes[f][0],k),0<=c[l][1]&&(e+='<span class="pk">-'+_DB.classes[f][4][c[l][1]]+"</span>"),e+="</div>";d=a[5];c='<span class="pki">'+_DB.teachers[d][0]+"</span>";e+='<div class="pk"';128>=U.getBrightness(h)&&(e+=' style="color:white;"');e+=">";e+=c;e+="</div>";e+="</div>";b+=e;return b+"</td>"}
function printRas(){var a=g_$td?getToolHeader()+$("#loadme").html():$("#mainFrame").html();$("#print-container").html(a);window.print()}
function getToolHeader(){var a=_DB.general,d;d="<div id='tool-header'><table cellpadding='0' cellspacing='0' width='100%'><tbody><tr><td width='30%'><div class='title' align='left'>"+a.school;d+="<br />"+a.shift;d=d+"</div</td><td width='40%'><div class='title' align='center'>"+("<h3>"+a.loc.rascas+"</h3>");d=d+"</div</td><td width='30%'<div class='title' align='right'>"+(a.loc.skgod+" "+a.year+"<br/>");d+=a.loc.vazi+" "+a.date;return d+"</div</td></tbody></table></div>"};
